name: inputs demo
on:
  workflow_dispatch:
    inputs:
      name:
        description: choose the env to deploy
        required: true
        default: dev
jobs:
  inputs-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the application
        run: |
          echo "Deploying the application to ${{ inputs.name }}"
        
